### ISSUE TITLE
Allow more config options

### ISSUE THREAD

**Issue by goingtosleep** [Issafalcon/lsp-overloads.nvim#9]
I just tried the plugin and really like it, doesn't have flickering issues like the previous plugin I was using. However the look of the floating is kind of strange, I used to have options like: `focusable, max_width, max_height`. It's great if the plugin allows users to change those, for now, I'm adding options to `lsp-overloads.handlers` as a workaround.

Thank you 😄

**Comment by Issafalcon** [comment]
Hi @goingtosleep , glad you like the plugin!

The extension of the floating window customization is definitely on my list of things to do. Admittedly, I've been pre-occupied with my neotest-dotnet adapter work and I've been neglecting this plugin a bit because of it. Adding some config options as you suggest shouldn't be too difficult though, so when I'm back from holiday in a couple of weeks. I'll look into adding them.

What was the last plugin you were using for this out of interest?

**Comment by goingtosleep** [comment]
Cool, thanks @Issafalcon.
I was using `lsp_signature.nvim`. It's a good plugin but somehow when I use `pylsp`, it keeps closing the signature help popup right after appearing. And when it doesn't close the popup, there is still flickering. The issues don't happen with your plugin 😁

**Comment by Issafalcon** [comment]
Ah, yeah. I was using lsp_signature, but it was because I needed something more geared towards handling overloaded methods, with more simplicity, that I created this. I found the flickering a bit annoying too 😃 

I've added some more of the popup config options in now. Hopefully it caters for all needs now. Let me know if it's missing anything else you'd like to see from a config point of view @goingtosleep

**Comment by goingtosleep** [comment]
Thanks a lot @Issafalcon. Actually I'm using the following configs:  
```
{
    focusable = true,
    focus = false,
    max_width = 80,
    max_height = 15,
    close_events = {'BufHidden', 'InsertLeave'},
}
```

Just the `close_events` is missing 😜. It's quite handy for me as it keeps the floating open. It's very nice if you could consider adding them. Thanks again and have a good weekend 😄

**Comment by Issafalcon** [comment]
Ah, I see. Yeah, close_events would be useful to override for sure. I'll line up some work to add that in as well

**Comment by Issafalcon** [comment]
#12
